heat_template_version: 2013-05-23

description: >
  Template based on https://github.com/openstack/heat-templates/blob/master/hot/servers_in_new_neutron_net.yaml

parameters:
  key_name:
    type: string
    description: Key name
  public_net:
    type: string
    description: Public network name
  github_pat:
    type: string
    description: GitHub PAT credential for cloning BEE
  git_branch:
    type: string
    description: git branch to checkout
  https_proxy:
    type: string
    description: HTTPS proxy url
  http_proxy:
    type: string
    description: HTTP proxy url
  no_proxy:
    type: string
    description: no proxy urls to set in environment
  nameservers:
    type: string
    description: list of nameservers separated by commas
  wfm_listen_port:
    type: string
    description: WFM listen port
  tm_listen_port:
    type: string
    description: TM listen port
  munge_key:
    type: string
    description: MUNGE key to be used for the cluster
  slurm_conf:
    type: string
    description: Slurm configuration file
resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: bee-net
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: '10.93.78.0/24'
      gateway_ip: '10.93.78.1'
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }
  main:
    type: OS::Nova::Server
    properties:
      name: bee-main
      # Custom snapshot with everything preinstalled
      image: 'debian-11-generic-amd64'
      flavor: 'm1.small'
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: main_port }
      user_data:
        str_replace:
          # template: { get_file: dora-setup.sh }
          template: { get_file: dora-slurm-nodes-2.sh }
          # Parameters added as input above need also be added here for
          # replacement
          params:
            $GITHUB_PAT: { get_param: github_pat }
            $USER: debian
            $GIT_BRANCH: { get_param: git_branch }
            $HTTPS_PROXY: { get_param: https_proxy }
            $HTTP_PROXY: { get_param: http_proxy }
            $NO_PROXY: { get_param: no_proxy }
            $NAMESERVERS: { get_param: nameservers }
            $WFM_LISTEN_PORT: { get_param: wfm_listen_port }
            $TM_LISTEN_PORT: { get_param: tm_listen_port }
            $MUNGE_KEY: { get_param: munge_key }
            $SLURM_CONF: { get_param: slurm_conf }
            $TYPE: "main"
  main_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }
          # Assign a fixed internal IP address
          ip_address: 10.93.78.4
  main_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: main_port }
  node0:
    type: OS::Nova::Server
    properties:
      name: bee-node0
      # Custom snapshot with everything preinstalled
      image: 'debian-11-generic-amd64'
      flavor: 'm1.small'
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node0_port }
      user_data:
        str_replace:
          # template: { get_file: dora-setup.sh }
          template: { get_file: dora-slurm-nodes-2.sh }
          # Parameters added as input above need also be added here for
          # replacement
          params:
            $GITHUB_PAT: { get_param: github_pat }
            $USER: debian
            $GIT_BRANCH: { get_param: git_branch }
            $HTTPS_PROXY: { get_param: https_proxy }
            $HTTP_PROXY: { get_param: http_proxy }
            $NO_PROXY: { get_param: no_proxy }
            $NAMESERVERS: { get_param: nameservers }
            $WFM_LISTEN_PORT: { get_param: wfm_listen_port }
            $TM_LISTEN_PORT: { get_param: tm_listen_port }
            $MUNGE_KEY: { get_param: munge_key }
            $SLURM_CONF: { get_param: slurm_conf }
            $TYPE: "node"
  node0_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }
          # Assign a fixed internal IP address
          ip_address: 10.93.78.5
outputs:
  main_public_ip:
    value: { get_attr: [main_floating_ip, floating_ip_address] }
